name: update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Update Readme
        run: |
          cd ${GITHUB_WORKSPACE}/update/
          go run main.go

      - name: Deploy
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update GitHub profile
          committer_name: GitHub Actions
          committer_email: actions@github.com
